name: RSA

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: where i am?
    - run: pwd
    - name: Generate keys
    - run: openssl genrsa -out private.key 256
        | openssl rsa -in private.key -outform PEM -pubout -out public.key
    - name: checking if theres or not
    - run: ls
      env:
        CI: true
