name: RSA

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: pwd
    - run: openssl genrsa -out private.key 256
    - run: openssl rsa -in private.key -outform PEM -pubout -out public.key
    - run: ls
    - run: less private.key
      env:
        CI: true
